name: 'Lint'
on:
  pull_request:
    branches:
      - master
      - main
  push: {}

jobs:
  check:
    name: 'run linter'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run Linter
        run: |
          npm run lint