name: 'Lint'
on:
  pull_request:
    branches:
      - master
      - main

jobs:
  check:
    name: 'run linter'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Npm Install
        run: |
          npm install --legacy-peer-deps
      - name: Run Linter
        run: |
          set -e
          npm run lint
